/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lucas
 */
import java.util.ArrayList; // import the ArrayList class
import javax.swing.ImageIcon;
public class blackJack extends javax.swing.JFrame {
    String types = "DSHC";
    ArrayList<cards> cards = newCards();
    ArrayList<cards> hand = new ArrayList<>();
    ArrayList<cards> dealer = new ArrayList<>();
    int playerT = 0;
    int dealerT = 0;
    int points = 100;//set to value before testing!!!!!!!!!!
    int wager = 0;
    Boolean winner;
    public blackJack() {
        initComponents();
        textBet.setEditable(true);
        textPoints.setEditable(false);
        textDealer.setEditable(false);
        textHand.setEditable(false);
    }
    public void start(){
        initComponents();
        if(Integer.parseInt(textBet.getText())>0 && Integer.parseInt(textBet.getText())<points){
            wager = Integer.parseInt(textBet.getText());
            textBet.setEditable(false);
        }
        else{
            textBet.setText("Enter Valid Bet");
        }
        dealer.add(cards.remove((int)(Math.random() * cards.size())));
        hand.add(cards.remove((int)(Math.random() * cards.size())));
        setHand();
    }
    public void updatePoints(){
        updateNote.selected.setPoints(points);
        updateNote.words.set(updateNote.selectedIndex+1, String.valueOf(points));
        updateNote.updateNotePad();
    }
    public ArrayList<cards> newCards(){
        ArrayList<cards> c = new ArrayList<>();
        for(int k = 1; k<=13; k++){
            int temp = 4;
            while(temp>0){
                c.add(new cards(k,types.substring(temp-1,temp)));
                temp--;
            }
        }
        return c;
    }
    public int getTotal(ArrayList<cards> c){
        int total = 0;
        boolean charlie = false;
        for(int k = 0; k<c.size(); k++){
            if (charlie && c.get(k).getNumber()==1 && total>21){
                total-=10;
            }
            if (c.get(k).getNumber()==1){
                if (total <= 11)
                    total+=1;
                else
                    total+=11;
                    charlie = true;
            }
            else if (c.get(k).getNumber()>10){
                total+=10;
            }
            else
                total+=c.get(k).getNumber();
        }
        return total;
    }
    public void setHand(){
        playerT = getTotal(hand);
        dealerT = getTotal(dealer);
        textDealer.setText(""+dealerT);
        textHand.setText(""+playerT);
    }
    public void hit(){
        hand.add(cards.remove((int)(Math.random() * cards.size())));
        setHand();
        if(playerT==21 || hand.size()==5){
            winner = true;
        }
        else if (playerT>21){
            winner = false;
        }
        setHand();
    }
    public void stand(){
        boolean win = false;
        while(!(win==false || win==true)){
            if(dealerT==21){
                winner = false;
            }
            else if(dealerT>21)
                winner = true;
            else if (dealerT<=17){
                if(dealerT>playerT)
                    winner = false;
                else if (playerT>dealerT)
                    winner = true;
            }
            else
                dealer.add(cards.remove((int)(Math.random() * cards.size())));
        }
        setHand();
        checkWin();
    }
    public void checkWin(){
        if (winner==true){
            points+=wager;
        }
        else if (winner==false){
            points-=wager;
        }
        updatePoints();
    }
    public void exit(){
        new gameCenter().setVisible(true);
        blackJack.this.setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        buttonHit = new javax.swing.JButton();
        buttonStand = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        textHand = new javax.swing.JTextField();
        buttonExit = new javax.swing.JButton();
        textDealer = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        buttonForfeit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        textBet = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        textPoints = new javax.swing.JTextField();
        buttonStart = new javax.swing.JButton();
        textDisplay = new javax.swing.JTextField();

        jLabel4.setText("jLabel4");

        jLabel5.setText("jLabel5");

        jTextField1.setText("jTextField1");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonHit.setText("Hit");
        buttonHit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHitActionPerformed(evt);
            }
        });

        buttonStand.setText("Stand");
        buttonStand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStandActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("BlackJack");

        textHand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textHandActionPerformed(evt);
            }
        });

        buttonExit.setText("Exit");
        buttonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExitActionPerformed(evt);
            }
        });

        jLabel2.setText("Your Hand");

        jLabel3.setText("Dealer's Hand");

        buttonForfeit.setText("Forfeit");
        buttonForfeit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonForfeitActionPerformed(evt);
            }
        });

        jLabel6.setText("Bet Amount");

        textBet.setText(" ");
        textBet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textBetActionPerformed(evt);
            }
        });

        jLabel7.setText("Points");

        textPoints.setText(" ");

        buttonStart.setText("Start");
        buttonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textBet)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel7))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(textPoints, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textHand, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addGap(105, 105, 105)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textDealer, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addComponent(buttonStart))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonHit, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonStand, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonForfeit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonExit)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textBet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textPoints, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textDealer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textHand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonStart))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonStand)
                    .addComponent(buttonHit)
                    .addComponent(buttonExit)
                    .addComponent(buttonForfeit)
                    .addComponent(textDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonHitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHitActionPerformed
    
    }//GEN-LAST:event_buttonHitActionPerformed

    private void buttonStandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonStandActionPerformed

    private void textHandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textHandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textHandActionPerformed

    private void buttonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExitActionPerformed
        exit();
    }//GEN-LAST:event_buttonExitActionPerformed

    private void buttonForfeitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonForfeitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonForfeitActionPerformed

    private void textBetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textBetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textBetActionPerformed

    private void buttonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStartActionPerformed
        start();
    }//GEN-LAST:event_buttonStartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(blackJack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(blackJack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(blackJack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(blackJack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new blackJack().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonExit;
    private javax.swing.JButton buttonForfeit;
    private javax.swing.JButton buttonHit;
    private javax.swing.JButton buttonStand;
    private javax.swing.JButton buttonStart;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField textBet;
    private javax.swing.JTextField textDealer;
    private javax.swing.JTextField textDisplay;
    private javax.swing.JTextField textHand;
    private javax.swing.JTextField textPoints;
    // End of variables declaration//GEN-END:variables
}
