/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lucas
 */
public class coinToss extends javax.swing.JFrame {

    /**
     * Creates new form coinToss
     */
    public coinToss() {
        initComponents();
        buttonHead.setEnabled(false);
        buttonTail.setEnabled(false);
        
    }
    int points = 0; // this needs to be connected to the notepad file and will be updated after existing the game
    int side = -1;
    int streak = 0;
    int topStreak = 0; // this requires to grab from the notepad file the topStreak Score from the list
    String topUser = ""; // as wel as this part
    
    
    
    public void checkStreak(){
        if (streak == topStreak){
                textTalk.setText("You are just one away from beating the Top 1 player!");
            }
            if (streak > topStreak){
                textTalk.setText("You are the new Top 1 player!");
                // Rewrite the notepad file to this coin flip game and change the Top1 player and highest streak
                textTopPlayer.setText(playerName);// be able to get the player name 
                textTopStreak.setText("Streak of"+streak); // some way to keep update this tab and update the topScore if the previous topStreak is gone;
                
            }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        buttonHead = new javax.swing.JButton();
        buttonTail = new javax.swing.JButton();
        textPoints = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textTalk = new javax.swing.JTextField();
        buttonPlay = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        textStreak = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        textTopPlayer = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        textTopStreak = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("WELCOME TO THE COIN MASTER");
        jLabel1.setSize(new java.awt.Dimension(45, 20));

        jLabel2.setText("Each toss costs 2 points. ");

        jLabel3.setText("Guessing the correct one gets you 3 points");

        jLabel4.setText("Guessing the wrong one will recieve nothing");

        buttonHead.setText("HEAD");
        buttonHead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHeadActionPerformed(evt);
            }
        });

        buttonTail.setText("TAIL");
        buttonTail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTailActionPerformed(evt);
            }
        });

        jLabel5.setText("Points in balance");

        textTalk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTalkActionPerformed(evt);
            }
        });

        buttonPlay.setText("Click to Play");
        buttonPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPlayActionPerformed(evt);
            }
        });

        jLabel6.setText("Guessing correctly in a row will get you bonus points");

        textStreak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textStreakActionPerformed(evt);
            }
        });

        jLabel7.setText("Streaks");

        jLabel8.setText("Top 1 Player");

        textTopStreak.setText("Streak of ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonHead)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonTail)
                                .addGap(37, 37, 37)
                                .addComponent(textStreak, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textTalk)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(0, 131, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(buttonPlay)
                        .addGap(69, 69, 69)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textPoints)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textTopPlayer)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel8))
                    .addComponent(textTopStreak))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2))
                    .addComponent(textPoints, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(textTopPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(buttonPlay)
                        .addComponent(jLabel7))
                    .addComponent(textTopStreak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonHead)
                    .addComponent(buttonTail)
                    .addComponent(textStreak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textTalk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPlayActionPerformed
        if(points>=2){
            buttonHead.setEnabled(true);
            buttonTail.setEnabled(true);
            points-=2;
            textTalk.setText("Heads or Tails?");
            side = (int)(Math.random()*1);
            buttonPlay.setEnabled(false);
        }
        else
            textTalk.setText("You don't got enough to play");
    }//GEN-LAST:event_buttonPlayActionPerformed

    private void buttonHeadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHeadActionPerformed
        if(side == 1){
            if (streak>=3){
                points+=5;
                textTalk.setText("You are on a row!!! Wins 5 points");
            }
            checkStreak();
            streak++;
            points+=3;
            textTalk.setText("It was heads! you won 3 points");
        }
        else{
            textTalk.setText("Oof wrong side. Wanna play again?");
            streak=0;
        }
        textStreak.setText(streak+"");
        buttonHead.setEnabled(false);
        buttonPlay.setEnabled(true);
    }//GEN-LAST:event_buttonHeadActionPerformed

    private void buttonTailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTailActionPerformed
        if(side == 0){
            if(streak>=3){
                points+=5;
                textTalk.setText("You are on a row!!! Wins 5 points");
            }
            checkStreak();
            points+=3;
            textTalk.setText("It was tails! You won 3 points");
            streak++;
        }
        else{
            textTalk.setText("Oof wrong side. Wanna play again?");
            streak=0;
        }
        textStreak.setText(streak+"");
        buttonTail.setEnabled(false);
        buttonPlay.setEnabled(true);
    }//GEN-LAST:event_buttonTailActionPerformed

    private void textTalkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTalkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTalkActionPerformed

    private void textStreakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textStreakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textStreakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new coinToss().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonHead;
    private javax.swing.JButton buttonPlay;
    private javax.swing.JButton buttonTail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField textPoints;
    private javax.swing.JTextField textStreak;
    private javax.swing.JTextField textTalk;
    private javax.swing.JTextField textTopPlayer;
    private javax.swing.JTextField textTopStreak;
    // End of variables declaration//GEN-END:variables
}
