import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.ArrayList;

public class coinToss extends javax.swing.JFrame {
    
    int points = updateNote.selected.getPoints(); // this needs to be connected to the notepad file and will be updated after existing the game
    int betPoints = 0;
    int side = 0;
    int streak = 0;
    int topStreak = 0; // this requires to grab from the notepad file the topStreak Score from the list
    String topUser = ""; // as wel as this part
    ArrayList<String> words = new ArrayList();
    int[] score; 
    
    public coinToss() {
        initComponents();
        buttonHead.setEnabled(false);
        buttonTail.setEnabled(false);
        buttonBet.setEnabled(false);
        textPoints.setText(points+"");
  
    }
    
    
    public void loadWords() {
        String currentDirectory = System.getProperty("user.dir");
        String fullFileName = currentDirectory + "/coin.txt";
        System.out.println("The file path is " + fullFileName);
        words.clear();
        try {   
                FileReader fr = new FileReader(fullFileName);
                BufferedReader br = new BufferedReader(fr);
                String line="";
                while( (line = br.readLine()) != null) {
                    System.out.println("Just read: " + line);
                    words.add(line);
                }
                br.close();
        }
        catch(Exception e) {
                System.out.println("Something went wrong file reading!");
        }
    }
    public void updateNotePad(){
        String currentDirectory = System.getProperty("user.dir");
        String fullFileName = currentDirectory + "/coin.txt";
        
        try {
            FileWriter fw = new FileWriter(fullFileName);
            BufferedWriter br = new BufferedWriter(fw);
           
            for(int k =0; k<words.size(); k++ ){
                br.write(words.get(k)+"\n");        
                
            }
            
            br.close();
        }
        catch(Exception e) {
            System.out.println("Error writing to file");
        }
        
    
    }
    
    
    public void checkStreak(){
            if (streak == topStreak){
                textTalk.setText("You are just one away from beating the Top 1 player!");
            }
            if (streak > topStreak){
                textTalk.setText("You are the new Top 1 player!");
                words.clear();
                words.add(updateNote.selected.getName());
                words.add(String.valueOf(streak));
                topStreak=streak;
                updateNotePad();
                // Rewrite the notepad file to this coin flip game and change the Top1 player and highest streak
                textTopPlayer.setText(updateNote.selected.getName());// be able to get the player name 
                textTopStreak.setText("Streak of"+topStreak); // some way to keep update this tab and update the topScore if the previous topStreak is gone;
                
            }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        buttonHead = new javax.swing.JButton();
        buttonTail = new javax.swing.JButton();
        textPoints = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textTalk = new javax.swing.JTextField();
        buttonPlay = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        textStreak = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        textTopPlayer = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        textTopStreak = new javax.swing.JTextField();
        buttonExit = new javax.swing.JButton();
        textBet = new javax.swing.JTextField();
        buttonBet = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("WELCOME TO THE COIN MASTER");
        jLabel1.setSize(new java.awt.Dimension(45, 20));

        jLabel2.setText("Bet the amount of points");

        jLabel3.setText("Guessing the correct one gets you the amount of points you bet");

        jLabel4.setText("Guessing the wrong one will remove the amount of points you bet");

        buttonHead.setText("HEAD");
        buttonHead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHeadActionPerformed(evt);
            }
        });

        buttonTail.setText("TAIL");
        buttonTail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTailActionPerformed(evt);
            }
        });

        textPoints.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPointsActionPerformed(evt);
            }
        });

        jLabel5.setText("Points in balance");

        textTalk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTalkActionPerformed(evt);
            }
        });

        buttonPlay.setText("Click to Play");
        buttonPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPlayActionPerformed(evt);
            }
        });

        jLabel6.setText("Guessing correctly in a row will get you bonus points");

        textStreak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textStreakActionPerformed(evt);
            }
        });

        jLabel7.setText("Streaks");

        jLabel8.setText("Top 1 Player");

        textTopStreak.setText("Streak of ");

        buttonExit.setText("Exit Game");
        buttonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExitActionPerformed(evt);
            }
        });

        textBet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textBetActionPerformed(evt);
            }
        });

        buttonBet.setText("Bet");
        buttonBet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textTalk)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel6))
                                .addGap(0, 50, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonHead)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonTail))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(buttonPlay)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonBet)
                                .addGap(49, 49, 49)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textBet, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(textStreak, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textPoints)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textTopPlayer)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel8))
                            .addComponent(textTopStreak))
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buttonExit)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2))
                    .addComponent(textPoints, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(textTopPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonPlay)
                    .addComponent(textTopStreak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonBet)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonExit)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(buttonHead)
                                    .addComponent(buttonTail))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textStreak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textBet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)))
                        .addComponent(textTalk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPlayActionPerformed
        loadWords();
        topUser = words.get(0);
        topStreak = Integer.parseInt(words.get(1));
        textTopPlayer.setText(topUser+"");
        textTopStreak.setText("Streak of "+ topStreak);
        if(points>0){
            buttonBet.setEnabled(true);
            side = (int)(Math.random()*2)+1;
            textTalk.setText("Heads or Tails?");
            buttonPlay.setEnabled(false);
        }
        else
            textTalk.setText("You don't got enough to play");
    }//GEN-LAST:event_buttonPlayActionPerformed

    private void buttonHeadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHeadActionPerformed
        if(side == 1){
            if (streak>=5){
                streak++;
                points+=betPoints*2;
                textTalk.setText("You are on a row!!! Wins "+betPoints*2+" points");
            }
            else{
                streak++;
                points+=betPoints;
                textTalk.setText("It was heads! you won "+betPoints+" points");
                checkStreak();
            }
        }
        else{
            textTalk.setText("Oof wrong side. Wanna play again?");
            streak=0;
            points-=betPoints;
            textPoints.setText(points+"");
        }
        textStreak.setText(streak+"");
        textPoints.setText(points+"");
        buttonHead.setEnabled(false);
        buttonTail.setEnabled(false);
        buttonPlay.setEnabled(true);
    }//GEN-LAST:event_buttonHeadActionPerformed

    private void buttonTailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTailActionPerformed
        if(side == 2){
            if(streak>=5){
                points+=betPoints*2;
                textTalk.setText("You are on a row!!! Wins "+betPoints*2+" points");
            }
            else{
                points+=betPoints;
                textTalk.setText("It was tails! You won "+betPoints+" points");
            }
            streak++;
            textPoints.setText(points+"");
            checkStreak();
        }
        else{
            textTalk.setText("Oof wrong side. Wanna play again?");
            streak=0;
            points-=betPoints;
            textPoints.setText(points+"");
        }
        textStreak.setText(streak+"");
        buttonTail.setEnabled(false);
        buttonHead.setEnabled(false);
        buttonPlay.setEnabled(true);
    }//GEN-LAST:event_buttonTailActionPerformed

    private void textTalkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTalkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTalkActionPerformed

    private void textStreakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textStreakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textStreakActionPerformed

    private void textPointsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPointsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPointsActionPerformed

    private void buttonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExitActionPerformed
        System.out.println("TOP ONE PRINTING");
        updateNote.selected.setPoints(points);
        updateNote.words.set(updateNote.selectedIndex+1, String.valueOf(points));
        updateNote.updateNotePad();
        System.out.println("PRint SOMETHIGN");
        new gameCenter().setVisible(true);
        coinToss.this.setVisible(false);
    }//GEN-LAST:event_buttonExitActionPerformed

    private void buttonBetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBetActionPerformed
        betPoints = Integer.parseInt(textBet.getText());
        if(points>=betPoints){
            buttonBet.setEnabled(false);
            buttonHead.setEnabled(true);
            buttonTail.setEnabled(true);
            textTalk.setText("you bet "+ betPoints);
            
        }
        else
            textTalk.setText("try something less, you don't have enough");
    }//GEN-LAST:event_buttonBetActionPerformed

    private void textBetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textBetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textBetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new coinToss().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBet;
    private javax.swing.JButton buttonExit;
    private javax.swing.JButton buttonHead;
    private javax.swing.JButton buttonPlay;
    private javax.swing.JButton buttonTail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField textBet;
    private javax.swing.JTextField textPoints;
    private javax.swing.JTextField textStreak;
    private javax.swing.JTextField textTalk;
    private javax.swing.JTextField textTopPlayer;
    private javax.swing.JTextField textTopStreak;
    // End of variables declaration//GEN-END:variables
}
